# Forward Propagation

In [2]:
import numpy as np
import math
import random

np.random.seed(101)

## **Create a NeuralNetwork class**

In [53]:
class NeuralNetwork():
    def __init__(self, dims):
        # take inputs dims = list of integers, number of nodes in each layer
        # create self.layers = list of layer weights as np.arrays
        # create self.bias_layers = list of layer weights as np.arrays (vectors)
        # also store self.num_layers
        self.num_layers = len(dims)
        self.layers = []
        self.bias_layers = []
        for l in range(self.num_layers-1):
            self.layers += [np.zeros((dims[l], dims[l+1]))]
            self.bias_layers += [np.ones((1, dims[l+1]))*-1]          
        pass
    
    def randomize_weights(self, min=-1, max=1):
        # loop through self.layers and self.bias_layers
        # set all values to random.uniform between min and max
        for l in range(len(self.layers)):
            for r in range(len(self.layers[l])):
                for c in range(len(self.layers[l][r])):
                    self.layers[l][r,c] = np.random.uniform(min, max)
            for b in range(len(self.bias_layers[l][0])):
                self.bias_layers[l][0][b] = np.random.uniform(min, max)

        pass
    
    def print_layers(self):
        for l,b  in zip(self.layers, self.bias_layers):
            print("layer")
            print(l)
            print("bias")
            print(b)
        

** Quick check of initializer **

In [54]:
nn = NeuralNetwork([2,4,1])
nn.print_layers()

layer
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
bias
[[-1. -1. -1. -1.]]
layer
[[0.]
 [0.]
 [0.]
 [0.]]
bias
[[-1.]]


In [55]:
nn.randomize_weights()

In [56]:
nn.print_layers()
"""
layer
d[[ 0.03279726  0.14133517 -0.94305155 -0.65695669]
 [ 0.37055396  0.66779373 -0.38606756  0.78722616]]
bias
[[ 0.44308772 -0.62012209  0.10845518 -0.29573609]]
layer
[[-0.63621519]
 [ 0.57120352]
 [ 0.93096644]
 [-0.53529268]]
bias
[[-0.83287713]]"""

layer
[[-0.62012209  0.10845518 -0.29573609 -0.63621519]
 [ 0.57120352  0.93096644 -0.53529268 -0.83287713]]
bias
[[ 0.20709684  0.45798551 -0.44752234  0.37061266]]
layer
[[ 0.03573495]
 [-0.90303093]
 [-0.72426152]
 [-0.62606515]]
bias
[[0.9886358]]


'\nlayer\nd[[ 0.03279726  0.14133517 -0.94305155 -0.65695669]\n [ 0.37055396  0.66779373 -0.38606756  0.78722616]]\nbias\n[[ 0.44308772 -0.62012209  0.10845518 -0.29573609]]\nlayer\n[[-0.63621519]\n [ 0.57120352]\n [ 0.93096644]\n [-0.53529268]]\nbias\n[[-0.83287713]]'

** Define sigmoid(x,k) with k default value=1 **

In [8]:
def sigmoid(x,k=1):
    return 1/(1+math.exp(-k*x))

** Define step(x) **

In [9]:
def step(x):
    return 1 if x>0 else 0

**Define forward_propagate(NN, x, A, verbose)**
  * This returns the (vector) output of feeding input vector "x" into Neural Net NN, with activation function A.
  * The 'verbose' flag tells whether to print the output of each layer. Default is False

In [82]:
def forward_propagate(NN, x, A, verbose = False):
    ## define this
    x = np.array([x])
    for l in range(len(NN.layers)):
        weighted = x.dot(NN.layers[l]) + NN.bias_layers[l]
        out = np.array([[A(w) for w in weighted[0]]])
        if verbose:
            print(out)
        x = out
    return x
    pass

# Test Output

Check the following outputs against your code

** Set the random seed to 101. Create a 2,2,1 Neural Network. Randomize its weights and print the layers **

In [83]:
np.random.seed(101)
NN = NeuralNetwork([2,2,1])
NN.randomize_weights()
NN.print_layers()
"""layer
[[ 0.03279726  0.14133517]
 [-0.94305155 -0.65695669]]
bias
[[ 0.37055396  0.66779373]]
layer
[[-0.38606756]
 [ 0.78722616]]
bias
[[ 0.44308772]]"""

layer
[[ 0.03279726  0.14133517]
 [-0.94305155 -0.65695669]]
bias
[[0.37055396 0.66779373]]
layer
[[-0.38606756]
 [ 0.78722616]]
bias
[[0.44308772]]


'layer\n[[ 0.03279726  0.14133517]\n [-0.94305155 -0.65695669]]\nbias\n[[ 0.37055396  0.66779373]]\nlayer\n[[-0.38606756]\n [ 0.78722616]]\nbias\n[[ 0.44308772]]'

** Define an input vector [10,20] and propagate it through the NN above. Show the output of each layer. **

In [84]:
x = [10,20]

forward_propagate(NN,x,sigmoid,verbose=True)

[[1.29456704e-08 1.57604953e-05]]
[[0.60899748]]


array([[0.60899748]])

** Create a 10,20,20,5 neural network with random weights and print its layers **

In [85]:
NN = NeuralNetwork([10,20,20,5])
NN.randomize_weights()
NN.print_layers()

"""layer
[[ -6.20122092e-01   1.08455182e-01  -2.95736092e-01  -6.36215195e-01
    5.71203524e-01   9.30966445e-01  -5.35292676e-01  -8.32877133e-01
    2.07096845e-01   4.57985515e-01  -4.47522343e-01   3.70612658e-01
    3.57349484e-02  -9.03030925e-01  -7.24261525e-01  -6.26065148e-01
    9.88635802e-01   4.13307934e-02   1.57579071e-01   4.69638117e-01]
 [  8.39235445e-02   8.26307115e-01   6.15840302e-01  -1.94004339e-01
   -2.85551314e-01   9.05753429e-01  -3.12736844e-01   7.30199633e-01
    6.60555424e-01   7.63228985e-02   8.44938745e-01  -8.05707040e-01
   -7.94305014e-01   4.03014591e-01   7.80959738e-01  -6.80879398e-01
   -4.48854910e-01   3.44983059e-01  -6.71393752e-01   4.02742273e-01]
 [ -2.47295556e-02   3.61355536e-01   4.30963847e-02  -9.13206611e-01
   -5.52126793e-01   1.50410174e-01  -7.59132680e-01   2.33427602e-04
   -7.23980863e-01  -8.94383198e-01  -6.43446155e-01  -1.15263737e-01
    7.55174649e-01   8.98528258e-01  -4.36651664e-02  -7.77613154e-02
    2.74578062e-01  -3.50784007e-01  -7.64843814e-01  -8.97798007e-01]
 [  2.75317306e-01   6.24531790e-01   3.40520841e-01   3.03535407e-01
   -1.50862113e-01   3.13190672e-01  -5.81677002e-01   3.19849038e-01
    5.92467975e-02   4.97040740e-01  -8.12486288e-01   5.69043700e-01
    3.74484075e-01   3.90156993e-01  -6.26696081e-03   9.50722254e-01
   -5.92944759e-01  -4.01959181e-01  -5.44688214e-01  -9.03662229e-01]
 [  8.07942715e-01  -8.39792923e-01   2.14432544e-01   2.61693407e-01
   -2.44116136e-01  -9.73517978e-01   6.84438824e-01  -2.30124508e-01
    1.03331690e-01   4.21076280e-01   3.50557701e-01   3.89129330e-01
   -3.15086464e-01  -1.75218873e-01  -5.20418069e-01   9.37671952e-01
   -4.22885985e-01  -7.05376775e-01  -7.41319120e-01   8.88112101e-01]
 [ -2.97131471e-01   4.67135226e-01   8.27779054e-01   4.01974988e-01
   -2.22937456e-01   8.84518578e-01   4.72982663e-01  -5.23071224e-01
    6.47547457e-01   5.21226890e-01  -2.10581852e-01  -5.99624165e-01
    4.25192947e-01   6.90617794e-01  -2.62706918e-01  -1.26039762e-01
   -2.86804671e-01  -5.20525186e-01   3.06756283e-01  -2.19121598e-01]
 [  3.15566036e-01  -2.75453290e-01  -2.86995972e-01  -6.09496799e-01
    9.74625501e-01  -9.53389015e-01   9.61608917e-02   1.21815789e-01
   -8.50490625e-01   7.84542018e-01  -7.78754177e-01   2.51546902e-01
   -7.98300763e-01   4.21705578e-01   7.62659010e-01   3.90579926e-01
   -4.67654602e-01   8.19927600e-01   1.59236725e-01  -2.80626210e-01]
 [  7.05268475e-01  -5.07641575e-01   5.60888211e-01  -9.08980678e-01
    7.70082377e-01  -4.47157559e-01   1.61848802e-01   8.21324525e-01
    9.85182093e-01  -8.75551921e-01   8.56962875e-01   3.43212124e-02
    8.90764172e-01   9.38621686e-02  -4.71676740e-01   2.94426962e-01
   -7.40292071e-02   2.62014304e-01   2.24725992e-02  -5.55238228e-01]
 [  4.68990778e-01   5.99322732e-01   7.53243317e-01  -3.94752396e-01
    2.18543330e-01  -8.29997833e-01  -3.61644348e-01   6.30998434e-01
    7.44812842e-01   7.81415104e-01   3.79819805e-01   8.31921089e-01
   -1.85609455e-01  -6.74779424e-01  -6.31817793e-01  -5.52457579e-01
   -9.97622678e-01  -5.46436622e-01   8.61958833e-01   4.77037105e-01]
 [  8.34954402e-01   2.06995922e-01  -9.11609176e-02  -3.73042211e-01
   -2.38036265e-01   2.85624024e-01   6.13065018e-01  -7.38944548e-01
    4.61130254e-01  -9.89123770e-01   3.01322647e-01  -9.39028753e-02
   -5.98709555e-01   2.62257955e-01  -9.64417483e-01   6.77101332e-01
    5.10920283e-02  -2.58124187e-01  -1.48500948e-01  -4.69809301e-01]]
bias
[[-0.10718476  0.96530647  0.50410838  0.04185239 -0.07523487 -0.86508659
   0.24567956  0.43923889 -0.09852811  0.36955476  0.46514286 -0.70039042
   0.21799102  0.72530777 -0.97675872  0.59982927  0.9069807  -0.78963954
  -0.10470271 -0.12445283]]
layer
[[  2.41391981e-01  -2.61655881e-01  -2.09347636e-01  -3.82857282e-01
    1.84164496e-01  -6.30410680e-01   9.34889644e-01   7.59007389e-01
   -7.60960086e-01   3.80175075e-01   8.08007653e-01   2.08258074e-01
   -1.71844733e-02   5.86304532e-01  -6.45950356e-01  -3.15940851e-01
   -4.88937062e-01  -5.34643009e-01   5.22233842e-01   8.86900768e-01]
 [ -4.43594880e-02  -9.38312669e-01   1.84239008e-01  -3.26453595e-01
    8.28228801e-03  -9.52507985e-01  -3.76727257e-01   7.15112987e-01
   -1.88086408e-01   1.51778052e-01   3.82314124e-01   7.27701481e-01
    6.67026889e-01   5.36046316e-01  -4.26659409e-01  -3.88351138e-01
    6.51807922e-01   1.41484233e-01  -5.03739358e-01  -9.74907537e-01]
 [ -3.34217480e-01  -2.14226365e-01   6.02602324e-01   7.91123535e-01
    5.10452193e-01   3.38063860e-01   6.50539262e-01  -8.74718261e-01
    5.61242600e-01  -8.65723341e-01  -7.35492811e-01   4.54205068e-01
   -4.97807768e-01   9.50249864e-02  -9.73144010e-01  -8.56145158e-01
   -7.25249976e-01  -3.17175938e-01   1.53311154e-01  -5.84583004e-01]
 [  8.46978224e-01  -4.84512429e-01   3.88655483e-01   5.19686391e-01
    9.95297991e-01   5.75029691e-01  -2.76037979e-01  -3.32104469e-01
    4.86438124e-01  -3.55541891e-01  -2.40060649e-01   3.86694470e-01
   -2.06243070e-01  -7.61297270e-01   1.42054375e-01  -6.34559465e-01
   -6.26940347e-02   8.76256298e-01  -1.12012718e-01   2.64747753e-01]
 [ -4.28361295e-01   2.17293934e-01   3.70660472e-01   6.40958413e-01
   -3.74810776e-01  -4.38264914e-01  -4.05234068e-01  -1.04688219e-01
    1.78888015e-01   7.69824916e-01   9.96808661e-01  -2.52185486e-01
   -7.98745023e-01   6.43303672e-01   4.41447814e-02   4.64584867e-01
    2.71336939e-01   3.00271346e-01   7.87856504e-01   6.46013614e-02]
 [ -6.09506927e-01  -7.54058202e-01   9.49252618e-01  -5.40241052e-01
   -5.47260556e-01   3.25577350e-01  -4.44254498e-02   4.26850684e-01
    4.15326549e-01  -2.45134726e-04  -7.46616011e-01   7.73267368e-01
   -5.80703736e-01  -1.38779229e-01   8.24535835e-01   8.78001146e-01
    1.57138533e-01   7.27547787e-01   3.67074684e-01  -4.08744159e-02]
 [ -1.13537087e-01  -7.60109948e-01  -1.16485767e-01  -1.31800384e-01
   -5.58167748e-02  -3.92243159e-01   7.78816404e-01  -9.80783330e-01
   -8.09848826e-01   3.39553889e-01  -1.83752722e-01   6.90794363e-01
   -3.76485659e-01   7.12147009e-01  -9.32524329e-01   9.84448621e-01
    9.32144223e-01   9.42423063e-01  -9.11902264e-01   8.40552455e-01]
 [  3.12612513e-01  -2.80307431e-02  -3.45251755e-01   8.30566533e-01
   -8.25086557e-01   7.09247439e-01  -4.61067539e-01   3.86375388e-02
    7.06191217e-02   7.40772405e-01  -9.38952369e-01   7.90871172e-01
   -8.00364352e-01   7.29605412e-01   8.24305592e-01   5.41101858e-01
   -9.29637543e-01  -2.87746090e-01   2.51135598e-01  -7.27601488e-01]
 [  6.48110896e-01  -9.97911885e-01   3.90788225e-01   1.29870945e-01
   -5.73712271e-01   2.34948377e-01   7.17649793e-01   4.24010422e-01
    2.89305026e-01   3.64240147e-01  -7.03850495e-02  -2.05915718e-01
   -7.95365343e-01  -9.45902374e-01  -1.10293372e-01   2.47949327e-01
   -3.51660348e-01   1.03810590e-01   3.83404893e-01  -9.20005210e-01]
 [  2.86074844e-01   6.85048260e-01   5.37430151e-01  -8.66961276e-01
   -2.61429349e-01  -2.45214597e-03  -1.96056648e-01  -6.31918026e-01
    7.92855735e-01   8.74176536e-01  -8.10193896e-01  -5.37885648e-01
   -9.99116010e-01   2.63610878e-02   6.08406368e-01  -2.19041894e-01
   -4.11453761e-01  -1.43190785e-01  -1.10683719e-01   9.05883022e-01]
 [ -9.67445779e-01  -4.85877259e-01  -9.89994695e-01   6.45164460e-02
    5.57600892e-01   6.77436136e-01   8.31115286e-01  -2.74618525e-01
    5.76791843e-02   6.48433153e-01   5.05302946e-01  -3.29281197e-01
    3.93543976e-01   7.66683686e-01  -8.79537455e-01   3.11509042e-01
   -3.12628671e-01  -3.69256571e-01   8.00368571e-01  -3.19137914e-01]
 [  9.49180245e-01   3.67764627e-01   1.58086462e-01   9.80610845e-01
   -5.37012405e-01  -8.64485748e-01  -9.11536498e-01   7.87801282e-01
    4.56461305e-01   4.33676612e-01   5.46363684e-01   5.14396926e-01
   -8.49619141e-01  -1.53002919e-01  -2.19328044e-01  -3.84455508e-02
    1.63261428e-01  -9.13569461e-01   8.78830174e-01   1.88001364e-01]
 [ -2.38818054e-01   9.90415612e-01  -4.11648170e-01  -5.12353065e-01
    9.61123983e-01  -1.70591759e-01   2.33760133e-01  -9.76377677e-01
    1.48936044e-01  -7.67958576e-01  -2.81323980e-01  -4.04407026e-01
   -6.80501193e-01  -2.99135070e-01   8.67981577e-01   5.46462042e-01
    8.14388244e-01  -8.52990474e-01  -2.55984582e-01  -3.20795713e-01]
 [ -7.36676955e-01   7.39414329e-01  -9.23936076e-01  -5.98342623e-01
   -6.66958214e-03   9.10143728e-01  -9.65725614e-01   5.25719312e-01
   -4.21138604e-01   1.24829076e-01  -8.33890625e-01   2.67544272e-01
   -3.02838959e-01   1.16417856e-01   6.11916618e-01   9.10652871e-01
    2.46372234e-01  -8.61734295e-01  -1.64682329e-01  -4.68233010e-01]
 [  5.56439683e-01   6.06590633e-01   1.98856671e-01  -8.40152800e-02
   -6.91125134e-01  -3.12648697e-01   1.96005107e-03   1.34814715e-01
   -9.29666777e-01   3.14241144e-01  -4.05454689e-01   1.91221353e-01
    2.15620725e-01  -4.57596365e-02   3.26960464e-01   1.87289647e-01
    6.55010877e-01  -3.32375383e-01  -4.33802622e-01  -4.24602620e-01]
 [ -9.56873319e-02   8.10859921e-01  -5.84597043e-01   9.40553974e-01
   -7.11690018e-01   1.27462257e-02   1.20719354e-01  -7.87159067e-01
   -7.20056966e-01   2.13830764e-01   5.30428440e-01  -4.84671397e-01
   -9.00291324e-01  -5.73516308e-01  -4.06101997e-01  -4.51963798e-01
   -7.73302018e-01   7.24012866e-01  -9.85906258e-01   3.52024425e-01]
 [  3.28203872e-01  -5.05961770e-01  -8.01282647e-01  -1.94886254e-01
   -8.22207581e-01  -9.69853441e-01   9.28219421e-01  -9.64516496e-01
   -9.67847208e-01  -8.12717146e-01   4.06443981e-01   7.20917220e-01
    7.33267725e-01  -8.77072757e-01   1.95052609e-01   1.04785508e-01
    6.16321761e-01   5.15282299e-01  -2.06957216e-01  -3.44030093e-02]
 [ -4.60628045e-01   2.32893152e-01   2.90706950e-01  -3.86775106e-02
    8.48983188e-01   3.87442756e-01   5.41607842e-01  -3.87587518e-01
    4.15575130e-01  -4.91250078e-01   9.58971318e-01  -3.70307013e-01
    4.56589526e-01  -9.79241074e-01  -6.22140469e-01  -9.28157090e-01
   -4.01533049e-01  -4.98535300e-01  -8.88372082e-01  -4.53246820e-03]
 [ -6.59213151e-01   7.97523073e-01   6.80451316e-01   6.56703949e-01
   -3.66373529e-02   8.03855837e-01  -5.29953230e-01  -4.05220979e-01
   -3.32224477e-01   7.52721778e-01  -4.68338511e-01  -5.10020844e-02
    1.25504290e-01  -6.61295344e-02   4.20266017e-01  -2.48397159e-01
    2.39104715e-01   5.06725485e-01   8.34526552e-01  -4.85570209e-01]
 [ -7.95700273e-01   9.95735564e-01  -7.36440300e-03   9.53652049e-01
    8.81237063e-01  -1.48904291e-01  -2.24386751e-01  -1.12514669e-01
   -3.59971466e-02   2.55097527e-01  -4.74041699e-01   9.72184409e-01
   -9.17053361e-01  -7.45026249e-01   2.45768834e-01   7.45709953e-01
    9.85225887e-01  -7.07556692e-03   8.01282513e-01   4.00506688e-01]]
bias
[[-0.60447916  0.8497596  -0.81863468 -0.15921065  0.59774893  0.3148014
   0.79390149 -0.63361556  0.16369934 -0.28768814 -0.35208901 -0.20826167
   0.95210485  0.64489057 -0.09395984 -0.17544323  0.14230462 -0.06326697
  -0.29140981  0.6978042 ]]
layer
[[ 0.52894909 -0.31131493 -0.03945489 -0.12517887  0.33940326]
 [ 0.05639792  0.9666912   0.6817093  -0.20222566 -0.30607469]
 [ 0.28296729 -0.0417536  -0.16307259  0.5991293   0.74005958]
 [ 0.66928159  0.21167498 -0.28992621  0.67219024 -0.25642741]
 [-0.46517083 -0.31617816  0.52842998  0.9433244  -0.80984148]
 [ 0.32838262  0.55274501 -0.00152774  0.30606982  0.06014379]
 [-0.06956764 -0.96146806  0.2593397  -0.13630854  0.56162195]
 [-0.22726251 -0.69044559 -0.49553621  0.73230388 -0.16125618]
 [ 0.302373   -0.46264789 -0.26216843  0.12550276  0.1387236 ]
 [-0.77277744 -0.83247779 -0.75873475 -0.25811831  0.16623981]
 [-0.20490911  0.58538314  0.56886692  0.63666832 -0.19893332]
 [-0.69623139  0.01425486  0.21978782 -0.76528498  0.20670267]
 [-0.54036495 -0.33797449 -0.66889435 -0.47387638 -0.76855359]
 [-0.55507634  0.21575435 -0.48915129 -0.23754295 -0.63690102]
 [-0.32928177  0.90975697  0.2668279  -0.09090188  0.35744473]
 [-0.2284732   0.54482236  0.53878934 -0.59817779  0.420151  ]
 [ 0.39066428  0.25359605  0.8966662  -0.11535017  0.41418009]
 [-0.4470131  -0.59722813 -0.26979441 -0.51216006 -0.19470578]
 [ 0.18917197 -0.16722511  0.18725371 -0.10476976  0.04060193]
 [-0.15338026  0.38202675 -0.40951628  0.90029941  0.51962566]]
bias
[[-0.11772897 -0.0425932   0.74881642  0.67606318  0.33540189]]"""

layer
[[-6.20122092e-01  1.08455182e-01 -2.95736092e-01 -6.36215195e-01
   5.71203524e-01  9.30966445e-01 -5.35292676e-01 -8.32877133e-01
   2.07096845e-01  4.57985515e-01 -4.47522343e-01  3.70612658e-01
   3.57349484e-02 -9.03030925e-01 -7.24261525e-01 -6.26065148e-01
   9.88635802e-01  4.13307934e-02  1.57579071e-01  4.69638117e-01]
 [ 8.39235445e-02  8.26307115e-01  6.15840302e-01 -1.94004339e-01
  -2.85551314e-01  9.05753429e-01 -3.12736844e-01  7.30199633e-01
   6.60555424e-01  7.63228985e-02  8.44938745e-01 -8.05707040e-01
  -7.94305014e-01  4.03014591e-01  7.80959738e-01 -6.80879398e-01
  -4.48854910e-01  3.44983059e-01 -6.71393752e-01  4.02742273e-01]
 [-2.47295556e-02  3.61355536e-01  4.30963847e-02 -9.13206611e-01
  -5.52126793e-01  1.50410174e-01 -7.59132680e-01  2.33427602e-04
  -7.23980863e-01 -8.94383198e-01 -6.43446155e-01 -1.15263737e-01
   7.55174649e-01  8.98528258e-01 -4.36651664e-02 -7.77613154e-02
   2.74578062e-01 -3.50784007e-01 -7.64843814e-01 -8.97798007e-01]
 

'layer\n[[ -6.20122092e-01   1.08455182e-01  -2.95736092e-01  -6.36215195e-01\n    5.71203524e-01   9.30966445e-01  -5.35292676e-01  -8.32877133e-01\n    2.07096845e-01   4.57985515e-01  -4.47522343e-01   3.70612658e-01\n    3.57349484e-02  -9.03030925e-01  -7.24261525e-01  -6.26065148e-01\n    9.88635802e-01   4.13307934e-02   1.57579071e-01   4.69638117e-01]\n [  8.39235445e-02   8.26307115e-01   6.15840302e-01  -1.94004339e-01\n   -2.85551314e-01   9.05753429e-01  -3.12736844e-01   7.30199633e-01\n    6.60555424e-01   7.63228985e-02   8.44938745e-01  -8.05707040e-01\n   -7.94305014e-01   4.03014591e-01   7.80959738e-01  -6.80879398e-01\n   -4.48854910e-01   3.44983059e-01  -6.71393752e-01   4.02742273e-01]\n [ -2.47295556e-02   3.61355536e-01   4.30963847e-02  -9.13206611e-01\n   -5.52126793e-01   1.50410174e-01  -7.59132680e-01   2.33427602e-04\n   -7.23980863e-01  -8.94383198e-01  -6.43446155e-01  -1.15263737e-01\n    7.55174649e-01   8.98528258e-01  -4.36651664e-02  -7.77613154e-

** Define a random length-10 input vector with values uniformly chosen from -10 to 10 **

In [86]:
x=np.random.uniform(-10,10,10)
print(x)
"""[-7.81254613  9.91117879  7.643992   -2.71816203 -3.38518934  5.99937355
 -8.83931214  9.53555237  4.49106612 -9.53338663]"""

[-7.81254613  9.91117879  7.643992   -2.71816203 -3.38518934  5.99937355
 -8.83931214  9.53555237  4.49106612 -9.53338663]


'[-7.81254613  9.91117879  7.643992   -2.71816203 -3.38518934  5.99937355\n -8.83931214  9.53555237  4.49106612 -9.53338663]'

** Propagate the vector through the neural network above **

In [87]:
forward_propagate(NN,x,sigmoid)
"""array([[ 0.189348  ,  0.54833771,  0.81944278,  0.52657077,  0.7133075 ]])"""

'array([[ 0.189348  ,  0.54833771,  0.81944278,  0.52657077,  0.7133075 ]])'