In [2]:
import numpy as np

In [4]:
a = [1, 2, 3]
b = [4, 5, 6]
a + b

[1, 2, 3, 4, 5, 6]

In [6]:
a = np.array(a)
b = np.array(b)
a + b

array([5, 7, 9])

In [9]:
a/b

array([0.25, 0.4 , 0.5 ])

In [11]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [16]:
np.dot(a,b)

32

In [17]:
np.cross(a,b)

array([-3,  6, -3])

In [22]:
np.dot(a, np.cross(a,b))

0

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.random.random((3,5))

array([[0.7188104 , 0.81491803, 0.27817518, 0.87595307, 0.56402105],
       [0.34030549, 0.73859343, 0.8867719 , 0.23105494, 0.92364194],
       [0.542241  , 0.17558507, 0.08764958, 0.72558582, 0.10968271]])